### PR TITLE
device section

### PR DESCRIPTION
**Pull request by jlurgo**
First pass, there's still more work to do to get to the perfect screenshot
image
image

### CODE REVIEW

**Comment by chfritz** [comment]
Thanks, I'll take a look later. Can you remove the "closes #29" comment, so we don't auto-close the ticket given that this is just a first pass? We'll still need to add the ros-tool things and polish the layout a bit.

**Comment by jlurgo** [comment]
done!

**Comment by chfritz** [comment]
I don't know why -- it doesn't seem to be explained by this PR -- but for some reason I can't open the page anymore. I get this in the server console:
```
[2024-10-29T03:57:51.546Z auth debug] not logged in /devices
[2024-10-29T03:57:51.612Z auth debug] not logged in /api/getJWT
```
and `GET http://localhost:3001/api/refresh 401 (Unauthorized)` in the browser console. I get the same in `upstream/main`.

**Comment by jlurgo** [comment]
hm yes, I tested today and got it, but went away after logging out/in. I'm pushing a fix, but I'll need to go back and get server side redirects working properly in a future pass...
Can you test it please @chfritz ?

**Review by chfritz — APPROVED** [review]

**Comment by chfritz** [comment]
Thanks for the fix. It's working now.

**Pull request merged**
