### PR TITLE
Code for getting JWT, replaced router

### PR DESCRIPTION
**Pull request by chfritz**
Some code I had in https://github.com/transitiverobotics/examples for getting a JWT from the front-end (we still need to add authentication). Also shows how to get env vars to the front-end in Vite.

Updated: also replace router with react-router.

### CODE REVIEW

**Comment by chfritz** [comment]
@jlurgo FYI

**Comment by chfritz** [comment]
Update: also create a JWT context to get jwt from server, stared adding transitive-sdk code.

For context: I'm currently working on a reactivity issue in remote-teleop reported by a user and for that I need a good test setup. TransAct is already really helpful for that, so I'm extending it to serve the test case I need rather than working with the old react example dashboards in https://github.com/transitiverobotics/examples.

**Comment by chfritz** [comment]
Added a FleetContext component that uses the Transitive SDK to get basic fleet data and expose it in a context. We can use that in the DeviceSelector.

**Review by jlurgo — APPROVED** [review]
LGTM

**Pull request merged**
